In [1]:
import pandas as pd

In [2]:
file_url = "http://storage.googleapis.com/download.tensorflow.org/data/heart.csv"
dataframe = pd.read_csv(file_url)

In [5]:
dataframe.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
dataframe.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal,0

In [8]:
subset = dataframe.sample(frac=.2)

In [9]:
subset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
112,58,0,4,100,248,0,2,122,0,1.0,2,0,normal,0
125,56,1,4,132,184,0,2,105,1,2.1,2,1,fixed,0
119,53,1,4,142,226,0,2,111,1,0.0,1,0,reversible,0
233,56,1,2,130,221,0,2,163,0,0.0,1,0,reversible,0
166,59,1,4,138,271,0,2,182,0,0.0,1,0,normal,0

In [10]:
subset.index

Int64Index([112, 125, 119, 233, 166,  45, 235, 133,  46, 256, 185,  56, 286,
            110, 294, 297, 100, 267, 277, 170, 182, 251, 292, 173, 213,   4,
            169, 127, 204,  34,  53, 143,  88,  41, 159,  51, 248, 106,  30,
             81, 253,  52,  35,  62, 270, 298, 264, 151, 282, 242, 238,  28,
            158, 121, 228, 302, 209, 295,  47,  97, 165],
           dtype='int64')

In [11]:
train_df = dataframe.drop(labels=subset.index)

In [12]:
train_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
5,56,1,2,120,236,0,0,178,0,0.8,1,0,normal,0

In [13]:
print(train_df.shape)
print(subset.shape)

(242, 14)
(61, 14)